apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cloud-cafe-prod
  labels:
    app: frontend
    app.kubernetes.io/part-of: cloud-cafe
spec:
  selector:
    app: frontend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cloud-cafe-prod
  labels:
    app: frontend
    app.kubernetes.io/part-of: cloud-cafe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: quay.io/alexeykazakov/cloud-cafe-frontend:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cloud-cafe
  namespace: cloud-cafe-prod
  labels:
    app: frontend
    app.kubernetes.io/part-of: cloud-cafe
spec:
  to:
    kind: Service
    name: frontend
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
